version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_KEY: ${API_KEY}
    ports:
      - "8080:80"
    environment:
      - API_KEY=${API_KEY}