name: portfolio
description: "A new Flutter project."

publish_to: "none"
version: "2.0.2+2024091401" #usar formato YYYYMMDD##

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  awesome_dio_interceptor: ^1.2.0
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^6.3.4
  fpdart: ^1.1.0
  geolocator: ^13.0.1
  intl: ^0.19.0
  intl_utils: ^2.8.7
  shared_preferences: ^2.3.2
  webview_flutter: ^4.9.0

  # Uncomment the following lines to enable the 'portfolio_ds' package from your local machine.
  # To set up the 'portfolio_ds' package, follow these step
  # portfolio_ds:
  #   path: ../portfolio_ds

  portfolio_ds:
    git:
      url: https://github.com/RenatoFloresV/portfolio_ds.git
      ref: main

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
